exclude: [build, debug, node_modules, spec, src, CNAME, Jakefile.js, reference-tpl.html, CHANGELOG.md, README.md, LICENSE, DOCS-TODO.md]

markdown: kramdown

kramdown:
  entity_output: as_input

latest_leaflet_version: 1.2.0

gems:
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from

# Integrity hashes for both leaflet.js and leaflet-src.js
# These will be shown in the downloads page
# See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
integrity_hash_css: "sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
integrity_hash_source: "sha512-YLT+I34kEPlk5OqR5XObf40B7sInrIU+bGe5VcwSpfR5OrFVjExFxfhVoJQEPZQWMyB53o3AU/bb5J91nc8CPA=="
integrity_hash_uglified: "sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
